KNOWLEDGE_BASE = [
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "HackerRank tests remain active indefinitely unless a start and end time are configured in test settings. To control expiration, open the test, go to Settings, then General, and update the Start date and End date fields. Clearing those fields keeps a test active indefinitely. When a test is expired, invited candidates cannot access it and new invitations may be disabled.",
        "escalate_if_matched": False,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "Test variants help teams adapt one assessment for different candidate profiles or technology stacks. Variants reduce duplicate test maintenance and allow role-specific reports, but a test needs at least two variants and variants without logic are hidden from candidates until logic is added.",
        "escalate_if_matched": False,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "To invite candidates to a HackerRank assessment, open the relevant test, go to the Candidates or Invite area, add candidate email addresses, confirm invitation settings, and send the invite. If the invite button is unavailable, check whether the test has expired or whether your account has permission to invite candidates.",
        "escalate_if_matched": False,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "To add extra time for a candidate, log in to HackerRank for Work, open Tests, select the test, go to Candidates, select the candidate, choose More, then Add Time Accommodation. Enter the accommodation percentage in multiples of five and save. Time accommodation can also be added before an invite is sent.",
        "escalate_if_matched": False,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "Compilation errors and IDE problems should first be checked against the selected language, compiler version, starter code, custom test cases, and browser environment. If the platform itself appears broken or multiple candidates are affected, collect the test name, candidate email, language, error message, and timestamp for support review.",
        "escalate_if_matched": True,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "Score disputes require careful review because scores depend on hidden test cases, language settings, plagiarism checks, and assessment configuration. Support should review the candidate email, test name, question name, expected score, observed score, and screenshots or logs before any scoring decision is changed.",
        "escalate_if_matched": True,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "Plagiarism detection and proctoring signals should be treated as review signals, not final proof in an automated support reply. Reports about cheating, suspicious activity, webcam violations, or copied code should be escalated to a human reviewer with candidate, test, and evidence details.",
        "escalate_if_matched": True,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "For HackerRank login problems, use the password reset flow from the login page. If the account was created through Google login and has no separate HackerRank password, use Forgot your password with the same email address to set a password before making account changes that require password confirmation.",
        "escalate_if_matched": False,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "Two-factor authentication issues can prevent login when a device is unavailable or codes fail. Users should try backup codes if available. If they cannot access the account or suspect compromise, the case should be reviewed by support with the account email and verification details.",
        "escalate_if_matched": True,
    },
    {
        "domain": "hackerrank",
        "product_area": "screen",
        "text": "Account hacked, suspicious login, unauthorized access, or unexpected account changes are sensitive account security issues. Do not provide account-specific recovery decisions in an automated response. Escalate these cases for identity and security review.",
        "escalate_if_matched": True,
    },
    {
        "domain": "hackerrank",
        "product_area": "community",
        "text": "To delete a HackerRank account created with Google login, first set a password using Forgot your password with the Google-linked email. Then log in, open profile settings, find the Delete Accounts section, and follow the prompts. Account deletion permanently removes data and cannot be undone.",
        "escalate_if_matched": False,
    },
    {
        "domain": "hackerrank",
        "product_area": "general_support",
        "text": "Billing, invoices, plan upgrades, subscription changes, and payment issues for HackerRank should be handled carefully. Provide general guidance only and route account-specific billing changes or disputes to HackerRank support or the account owner.",
        "escalate_if_matched": True,
    },
    {
        "domain": "hackerrank",
        "product_area": "general_support",
        "text": "Recruiter permissions and roles determine whether a user can create tests, invite candidates, view reports, or change account settings. If a user cannot perform an action, they should ask an admin to check their role and team permissions.",
        "escalate_if_matched": False,
    },
    {
        "domain": "hackerrank",
        "product_area": "general_support",
        "text": "For general HackerRank questions, identify whether the issue is about tests, candidates, account access, billing, permissions, or community profile settings. If the request is unclear or unsupported by available documentation, recommend contacting support.",
        "escalate_if_matched": False,
    },
    {
        "domain": "claude",
        "product_area": "general_support",
        "text": "Claude offers different access levels such as free and paid plans. Plan limits, message quotas, and feature access can vary by plan and usage. If a user asks about their exact subscription state, billing charge, or account-specific limit, they should check account settings or contact Claude support.",
        "escalate_if_matched": False,
    },
    {
        "domain": "claude",
        "product_area": "general_support",
        "text": "Claude Pro subscription and billing questions may involve invoices, renewals, cancellations, or unexpected charges. General plan guidance can be provided from documentation, but refunds, disputed charges, and account-specific billing decisions should be escalated.",
        "escalate_if_matched": True,
    },
    {
        "domain": "claude",
        "product_area": "general_support",
        "text": "Claude API access is separate from normal chat usage and is intended for developers building applications. Commercial use, API keys, rate limits, and usage billing should be managed through the API console and relevant Anthropic support channels.",
        "escalate_if_matched": False,
    },
    {
        "domain": "claude",
        "product_area": "screen",
        "text": "For Claude account login or password problems, use the sign-in and password reset options associated with the account email. If the account is inaccessible, suspended, or appears compromised, route the case to support for account review.",
        "escalate_if_matched": True,
    },
    {
        "domain": "claude",
        "product_area": "privacy",
        "text": "Claude conversations can be managed from the conversation interface. To delete an individual conversation, open the conversation, select the conversation name at the top, and choose Delete from the available options.",
        "escalate_if_matched": False,
    },
    {
        "domain": "claude",
        "product_area": "privacy",
        "text": "Privacy, data deletion, GDPR, and personal data requests require careful handling. Users can manage some conversations directly, but formal privacy rights requests or requests involving personal data review should go through Claude support or privacy channels.",
        "escalate_if_matched": True,
    },
    {
        "domain": "claude",
        "product_area": "conversation_management",
        "text": "Projects and conversation management features help organize Claude work. Users can rename or delete conversations where supported, and should avoid sharing private information when they do not want it retained in a normal conversation.",
        "escalate_if_matched": False,
    },
    {
        "domain": "claude",
        "product_area": "general_support",
        "text": "Claude can help with writing, analysis, coding, summarization, and reasoning tasks, but responses may have limitations and should be checked for important decisions. Product-specific problems should be handled using Claude support documentation or support channels.",
        "escalate_if_matched": False,
    },
    {
        "domain": "claude",
        "product_area": "general_support",
        "text": "Claude message quotas and rate limits can depend on plan, demand, and usage. If a user reaches a limit, they may need to wait for quota reset, reduce usage, or review plan options. Exact account limits should be checked in account settings or with support.",
        "escalate_if_matched": False,
    },
    {
        "domain": "claude",
        "product_area": "screen",
        "text": "Account suspension, permanent bans, policy enforcement, and appeals are sensitive issues. Automated support should not decide these cases. Escalate to Claude support for human review.",
        "escalate_if_matched": True,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "For a lost or stolen Visa card in India, call Visa India at 000-800-100-1219. From outside India, Visa Global Customer Assistance Service is available at +1 303 967 1090 and can help block the card and arrange emergency assistance.",
        "escalate_if_matched": False,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "Unauthorized transactions, fraudulent card use, suspicious activity, or a stolen card should be handled urgently. The cardholder should contact their card issuer or Visa support immediately so the card can be blocked and the issue reviewed.",
        "escalate_if_matched": True,
    },
    {
        "domain": "visa",
        "product_area": "travel_support",
        "text": "For stolen Citicorp Visa Traveller's Cheques, call Citicorp immediately at 1-800-645-6556 or collect at 1-813-623-1709, Monday to Friday 6:30 am to 2:30 pm EST. Have the cheque serial numbers, purchase details, loss details, and issuer name ready. Notify local police if the cheques were lost or stolen while travelling.",
        "escalate_if_matched": False,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "Disputes and chargebacks are normally handled by the card issuer rather than Visa directly. Cardholders should contact the bank or financial institution that issued the card and provide transaction details, merchant name, amount, and date.",
        "escalate_if_matched": True,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "If a Visa card is declined or blocked, the cardholder should contact the card issuer shown on the back of the card. Declines can happen for issuer controls, suspected fraud, insufficient funds, card status, or transaction restrictions.",
        "escalate_if_matched": False,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "PIN resets are handled by the bank or financial institution that issued the Visa card. Visa does not set or recover a cardholder PIN directly. Contact the issuer through the number on the card or the issuer's official channels.",
        "escalate_if_matched": False,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "International transaction fees and currency conversion charges are set by the card issuer and cardholder agreement. Cardholders should check their statement or contact the issuer for exact fees on international purchases.",
        "escalate_if_matched": False,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "Contactless payment issues can be caused by terminal limits, card issuer restrictions, damaged cards, or merchant acceptance. Try a chip or swipe transaction if available and contact the card issuer if contactless continues failing.",
        "escalate_if_matched": False,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "ATM withdrawal problems may be related to issuer limits, ATM availability, fees, network issues, or card status. The cardholder should keep any receipt and contact the issuing bank for account-specific investigation.",
        "escalate_if_matched": False,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "Visa checkout or online payment help depends on the merchant, issuer, and checkout flow. If a payment does not complete, verify card details, billing information, merchant acceptance, and issuer approval. Contact the issuer for account-specific declines.",
        "escalate_if_matched": False,
    },
    {
        "domain": "visa",
        "product_area": "general_support",
        "text": "General Visa card questions are often best answered by the card issuer because the issuer manages the account, fees, PIN, limits, disputes, and approvals. Visa support can help with global assistance and routing.",
        "escalate_if_matched": False,
    },
    {
        "domain": "general",
        "product_area": "conversation_management",
        "text": "Out-of-scope questions unrelated to HackerRank, Claude, or Visa should receive a brief response explaining that the request is outside support scope. Polite thanks and greetings can be acknowledged without escalation.",
        "escalate_if_matched": False,
    },
]
